### ISSUE TITLE
BenchmarkList file disappears 

### ISSUE THREAD

**Issue by sshakil** [ignl/BinarySearchTrees#1]
Trying to run individual benchmark files in Eclipse is running into this:
 java -jar benchmarks.jar 

```
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:96)
at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:104)
at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:251)
at org.openjdk.jmh.runner.Runner.run(Runner.java:203)
at org.openjdk.jmh.Main.main(Main.java:69)
```

Running the Eclipse-generated benchmarks.jar file also gives the same error.

It works fine when using from CLI, as per your instructions.  Upon doing so, I see the BenchmarkList and CompilerHints files under target/classes/META-INF, and so too in the generated jar.  This is not the case when running from within Eclipse.  I've tried recreating the project a couple of times, making sure to use the same JMH archetype and version (1.7.1), but no dice.

This appears to be an issue with the IDE not generating or not keeping around the BenchmarkList and CompilerHints files, somehow related to the JMH library and possibly its maven archetype.  Are these generated, or hand written?  If they're hand written, a workaround would be to stash them in a resource directory.

I'm wondering what your IDE setup looks like, if you're using one, and if so - how you may have managed to avoid or got around this issue.

**Comment by sshakil** [comment]
I do see a difference in the compilation when using Eclipse and when using CLI.

Eclipse

```
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Trees 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Trees ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/admin/dev/workspaces/public/Trees/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Trees ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Trees ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/admin/dev/workspaces/public/Trees/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Trees ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ Trees ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Trees ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/admin/dev/workspaces/public/Trees/target/Trees-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-shade-plugin:2.2:shade (default) @ Trees ---
[INFO] Including org.openjdk.jmh:jmh-core:jar:1.7.1 in the shaded jar.
[INFO] Including net.sf.jopt-simple:jopt-simple:jar:4.6 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.2 in the shaded jar.
[INFO] Including junit:junit:jar:4.11 in the shaded jar.
[INFO] Including org.hamcrest:hamcrest-core:jar:1.3 in the shaded jar.
[INFO] Replacing /Users/admin/dev/workspaces/public/Trees/target/benchmarks.jar with /Users/admin/dev/workspaces/public/Trees/target/Trees-0.0.1-SNAPSHOT-shaded.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ Trees ---
[INFO] Installing /Users/admin/dev/workspaces/public/Trees/target/Trees-0.0.1-SNAPSHOT.jar to /Users/admin/.m2/repository/org/intelligentjava/Trees/0.0.1-SNAPSHOT/Trees-0.0.1-SNAPSHOT.jar
[INFO] Installing /Users/admin/dev/workspaces/public/Trees/pom.xml to /Users/admin/.m2/repository/org/intelligentjava/Trees/0.0.1-SNAPSHOT/Trees-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.090 s
[INFO] Finished at: 2015-07-08T05:37:51-05:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

CLI:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Trees 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Trees ---
[INFO] Deleting /Users/admin/dev/src/public/BinarySearchTrees/Trees/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.334 s
[INFO] Finished at: 2015-07-08T05:40:54-04:00
[INFO] Final Memory: 6M/245M
[INFO] ------------------------------------------------------------------------
Saads-MacBook-Pro:Trees admin$ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Trees 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Trees ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/admin/dev/src/public/BinarySearchTrees/Trees/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Trees ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 23 source files to /Users/admin/dev/src/public/BinarySearchTrees/Trees/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Trees ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/admin/dev/src/public/BinarySearchTrees/Trees/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Trees ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 14 source files to /Users/admin/dev/src/public/BinarySearchTrees/Trees/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ Trees ---
[INFO] Surefire report directory: /Users/admin/dev/src/public/BinarySearchTrees/Trees/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.intelligentjava.algos.simplestructures.LinkedListTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec - in org.intelligentjava.algos.simplestructures.LinkedListTest
Running org.intelligentjava.algos.simplestructures.QueueTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.intelligentjava.algos.simplestructures.QueueTest
Running org.intelligentjava.algos.simplestructures.StackTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.intelligentjava.algos.simplestructures.StackTest
Running org.intelligentjava.algos.trees.AVLTreeTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.intelligentjava.algos.trees.AVLTreeTest
Running org.intelligentjava.algos.trees.BinarySearchTreeTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.intelligentjava.algos.trees.BinarySearchTreeTest
Running org.intelligentjava.algos.trees.RedBlackTreeTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in org.intelligentjava.algos.trees.RedBlackTreeTest
Running org.intelligentjava.algos.trees.ScapegoatTreeTest
         /----- 18
         |       \----- 17
 /----- 16
 |       |       /----- 15
 |   
    \----- 14
....
```

I'll investigate this more.

**Comment by sshakil** [comment]
I was originally using a project in which my source folders were linked folders (to keep source and eclipse project files and folders separated, in order to remove the need to manage exclusions, etc).  I just tried a local clone in which the source sits next to the eclipse project files, with artifactId Trees2, and it works fine.  So either the artiffactId change did the trick, or the source has to sit right next to the eclipse project files (_sigh_).  It's likely the source location.

Update: Importing  "Existing maven project" also worked, with the added benefit of magically being a git-managed project from within Eclipse (the above local clone wasn't).  Importing didn't work the first time, though!  As mentioned before, I ended up recreating the project both using CLI and using Eclipse (had to manually add the archetype).  I don't know exactly why it didn't see the pom the first time.  A guess here but this could be because Eclipse wasn't aware of the JHM archetype initially (which wasn't present on the combined local and external list). Perhaps the act of recreating it and adding the archetype allowed a subsequent successful import.

**Comment by ignl** [comment]
Hi, I use eclipse, but only for coding and unit tests. I actually never tried to run benchmarks directly from eclipse so I probably can't help you much :) As far as I know JHM generates some code with its maven plugin, and probably it didn't work from eclipse.
